import "./globals.css";
import Link from 'next/link'; // a태그보다 최적화되어 빠르게 페이지 빌드가 가능함.
import { Control } from "./Control";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by Sung",
};

export default async function RootLayout({ children }) {
   
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', {cache:'no-store'});
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {
            topics.map((topic)=>{
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            })
          }
        </ol>
        {children}
        <Control  />
      </body>
    </html>
  );
}
